import React from "react";
import Sidebar from "../components/Sidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Breadcrumbs from "../components/Breadcrumbs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Invoice App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div className="flex min-h-screen bg-etuwaCustom-wb">
          {/* Sidebar takes fixed width, full height */}
          <div className="w-[200px] h-screen">
            <Sidebar />
          </div>

          {/* Main content (children) grows to fill remaining space */}
          <main className="flex-1 overflow-auto">
            <Breadcrumbs />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
